server:
  port: 8080
order:
  isOpen: 1

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mi20030610.
    url: jdbc:mysql://localhost:3306/blog
  web:
    resources:
      static-locations: file:F:\\elmImg